In [1]:
%matplotlib inline


In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[1.1534e-15, 7.7071e-43, 1.1534e-15],
        [7.7071e-43, 1.1534e-15, 7.7071e-43],
        [1.1534e-15, 7.7071e-43, 1.1534e-15],
        [7.7071e-43, 1.1534e-15, 7.7071e-43],
        [1.1534e-15, 7.7071e-43, 1.1534e-15]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6133, 0.5874, 0.7197],
        [0.7298, 0.9912, 0.0098],
        [0.5020, 0.4386, 0.0472],
        [0.2070, 0.4588, 0.5790],
        [0.5425, 0.3465, 0.8352]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 方法来创建对象
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 覆盖 dtype!
print(x)                                      #  对象的size 是相同的，只是值和类型发生了变化

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.4186, -1.1911, -0.0371],
        [ 1.6850,  0.0631, -0.8447],
        [-0.4812,  0.5391,  0.3165],
        [-0.2751, -0.2253,  1.4941],
        [ 0.2788, -0.1177,  0.5523]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.5063, -0.2579,  0.2793],
        [ 2.1136,  0.7240, -0.0069],
        [ 0.4946,  0.7377,  1.2054],
        [ 0.4801, -0.0173,  1.8464],
        [ 1.1716,  0.0381,  1.5260]])


In [10]:

print(torch.add(x, y))

tensor([[-0.5063, -0.2579,  0.2793],
        [ 2.1136,  0.7240, -0.0069],
        [ 0.4946,  0.7377,  1.2054],
        [ 0.4801, -0.0173,  1.8464],
        [ 1.1716,  0.0381,  1.5260]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.5063, -0.2579,  0.2793],
        [ 2.1136,  0.7240, -0.0069],
        [ 0.4946,  0.7377,  1.2054],
        [ 0.4801, -0.0173,  1.8464],
        [ 1.1716,  0.0381,  1.5260]])


In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.5063, -0.2579,  0.2793],
        [ 2.1136,  0.7240, -0.0069],
        [ 0.4946,  0.7377,  1.2054],
        [ 0.4801, -0.0173,  1.8464],
        [ 1.1716,  0.0381,  1.5260]])
